typography_spectrum: 0.799549
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.31118061022974397
  lightness: 0.6531261622525447
  rhythmicContrast: 0.7587181047409155
  saturation: 0.8217731710451923
opengraph: {}
layout_spectrum: 0.7153092329661325
analytics: {}
author:
  name: Cathy
  email: c.holloway@ucl.ac.uk
name: 'Cathyholloway '
cta: {}
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7e13cbb2-bada-4721-b87a-b01e3d65711e.ico
title: Happy when making
purpose: {}
